# Generated by Django 5.2.5 on 2025-08-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encurtador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='link_custom',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='link_original',
            field=models.URLField(),
        ),
    ]
